services:
  issuer_frontend:
    image: ghcr.io/eu-digital-identity-wallet/eudi-srv-web-issuing-frontend-eudiw-py:latest
    ports:
      - "6007:5000"
    volumes:
      - /tmp/issuer_frontend/log_dev:/tmp/issuer_frontend/log_dev
    env_file:
      - .env
    restart: unless-stopped
    profiles: ["base"]

  issuer_frontend_local:
    image: ghcr.io/eu-digital-identity-wallet/eudi-srv-web-issuing-frontend-eudiw-py:latest
    command: flask run --host=0.0.0.0 --cert=/certs/tls/localhost+2.pem --key=/certs/tls/localhost+2-key.pem
    ports:
      - "6007:5000"
    volumes:
      - ../eudi-srv-issuer-oidc-py/script/certs/tls/localhost+2.pem:/certs/tls/localhost+2.pem:ro
      - ../eudi-srv-issuer-oidc-py/script/certs/tls/localhost+2-key.pem:/certs/tls/localhost+2-key.pem:ro
      - /tmp/issuer_frontend/log_dev:/tmp/issuer_frontend/log_dev
    env_file:
      - .env.local
    restart: unless-stopped
    profiles: ["local"]